### ISSUE TITLE
java.lang.NoSuchMethodError: android.view.View.getMeasuredState

### ISSUE THREAD

**Issue by shivakumars** [pakerfeldt/android-viewflow#96]
Hi,

I am using ViewFlow library in a android app which runs on Android 2.3.7. And i am getting this error, FYI I have passed onConfigurationChanged to viewflow

```
java.lang.NoSuchMethodError: android.view.View.getMeasuredState
    at org.taptwo.android.widget.ViewFlow.onMeasure(ViewFlow.java:171)
    at android.view.View.measure(View.java:8366)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
    at android.view.View.measure(View.java:8366)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
    at   android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
    at                android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
    at android.view.View.measure(View.java:8366)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
    at android.view.View.measure(View.java:8366)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
    at android.view.View.measure(View.java:8366)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
    at android.view.View.measure(View.java:8366)
    at android.view.ViewRoot.performTraversals(ViewRoot.java:844)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1865)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)
```

Let me know if you can help me on this.

**Comment by adouggy** [comment]
same issue, after adding project from exists code, compile failed with this notice

**Comment by adouggy** [comment]
see issue #95
